<a href="https://colab.research.google.com/github/Delena7/MDS/blob/main/Math_1_%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
#Задание 1
#Создайте матрицу 3 на 3, заполненную числами от 1 до 9
A1=np.arange(1,10).reshape(3,3)
A1

A2=np.eye(3)
A2

#Прибавьте к ней матрицу с единицами на диагонале
A3=A1+A2
A3

#Умножьте полученную матрицу на вектор (1, 2, 3)
v=(1,2,3)
A4=A3@v
A4

#Вычислить транспонированную матрицу от полученной в результате прибавления матрицы
A5=np.transpose(A3)
A5

#Посчитайте обратную матрицу к полученной в результате прибавления матрице
A6=np.linalg.inv(A3)
A6

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [5]:
#Уровень 1: Задание 2 Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2], [1, 3]])
np.linalg.eig(m)
#print(m)

#Задание 3 Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.
#P.S. Матрица должна быть ненулевой и размерностью не менее 2!
m1=np.array([[2,1],[1,1]])
det1=np.linalg.eig(m1)
print(m1)
print(det1)
det = 0

while det != 1:
    a = np.random.randint(-10,10,(3,3))
    det=np.linalg.det(a)

print('искомая матрица: \n',a)

[[2 1]
 [1 1]]
EigResult(eigenvalues=array([2.61803399, 0.38196601]), eigenvectors=array([[ 0.85065081, -0.52573111],
       [ 0.52573111,  0.85065081]]))
искомая матрица: 
 [[-1  1 -5]
 [ 3  1 -8]
 [-3  0  2]]
